

export const APP_FEATURES=[
    {
        id:"01",
        title:"Tailored just fro you",
        description:"Get Interview Question and model answer based on your role, experience,and specific focus area "
    },
    {
        id:"02",
        title:"Learn at your own Pace",
        description:"Expand answer only when you're ready. Dive deeper into any concept instantly with AI-powered detailed "
    },
    {
        id:"03",
        title:"Capture your Insights",
        description:"Add personal notes to any question and pins important ones to the top - making your learning more organized"
    },
    {
        id:"04",
        title:"understand the why behind the answer",
        description:"Beyond just answer, unlock detailed explanation generated by AI to grasp the underlying concepts and reasoning"
    },
    {
        id:"05",
        title:"Save,organize and share",
        description:"Bookmark your favorite questions for quick access later. Share insightful questions and answers with friends or mentors"
    }
];
